language: c
compiler: gcc
sudo: required
git:
  depth: 2
cache:
  apt: true
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq cmake libssl-dev doxygen pkg-config
script:
  - mkdir -p build
  - pushd build
  - >
    cmake ..
    -DOPENELP_BUNDLE_PCRE:BOOL=On
  - popd
  - make -C build -j2
  - make -C build -j2 check
  - make -C build -j2 doc
